apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:  
  name: customhpa
  namespace: default    
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: frontend
  metrics:
    - type: Object
      object:
        metric: 
          name: rabbitmq_queue_messages_my_custom_queue
        describedObject:
          apiVersion: v1
          kind: Service
          name: newCustomService
        target: 
          type: AverageValue
          averageValue: 10